### PR TITLE
Handling App Links from Android M and handles no intent case

### LINKED ISSUE #1: When App links are enabled web browser does not appear for non handled links.
1. Android M + App links manually enabled for Slinger Example (example.com)
2. `adb shell am start -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d "http:
   //example.com/meh"`
3. Crash - no Activities can handle this.

```
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime: FATAL EXCEPTION: main
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime: Process: pl.allegro.android.slinger.sample, PID: 15657
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{pl.allegro.android.slinger.sample/pl.allegro.android.slinger.example.ExampleSlingerActivity}: java.lang.IllegalArgumentException
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:  Caused by: java.lang.IllegalArgumentException
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at java.util.AbstractList.subList(AbstractList.java:736)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at pl.allegro.android.slinger.IntentStarter.getIntentList(IntentStarter.java:164)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at pl.allegro.android.slinger.IntentStarter.showChooser(IntentStarter.java:155)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at pl.allegro.android.slinger.IntentStarter.startActivity(IntentStarter.java:142)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at pl.allegro.android.slinger.SlingerActivity.excludeSlingerAndStartTargetActivity(SlingerActivity.java:37)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at pl.allegro.android.slinger.SlingerActivity.onCreate(SlingerActivity.java:27)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6237)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148) 
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417) 
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
10-19 17:10:04.830 15657-15657/pl.allegro.android.slinger.sample E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

### PR DESCRIPTION
**Pull request by kkocel**
Fixes #1

### CODE REVIEW

File: slinger/src/main/java/pl/allegro/android/slinger/AppLinkBypasser.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+import android.content.pm.PackageManager;
+import android.content.pm.ResolveInfo;
+import android.net.Uri;
+import android.os.Build;
+import android.support.annotation.VisibleForTesting;
+import java.util.List;
+
+/**
+ * Class bypassing App link mechanism introduced in Android Marshmallow.
+ * If an application has link-handling setting enabled then {@link PackageManager} returns only ony
```
Comment (jakubkrolewski) [inline slinger/src/main/java/pl/allegro/android/slinger/AppLinkBypasser.java]: ony -> one

File: slinger/src/main/java/pl/allegro/android/slinger/AppLinkBypasser.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+  boolean isBypassApplicable(List<ResolveInfo> queryIntentActivities) {
+    return hasMarshmallow() && onlyOneResult(queryIntentActivities);
+  }
+
+  private boolean onlyOneResult(List<ResolveInfo> queryIntentActivities) {
+    return queryIntentActivities.size() == 1;
+  }
+
+  private boolean hasMarshmallow() {
+    return Build.VERSION.SDK_INT > Build.VERSION_CODES.LOLLIPOP_MR1;
```
Comment (jakubkrolewski) [inline slinger/src/main/java/pl/allegro/android/slinger/AppLinkBypasser.java]:
```
>= MARSHAMALLOW?
```

File: slinger/src/main/java/pl/allegro/android/slinger/IntentStarter.java [hunk 3]
```diff
@@ -138,8 +145,10 @@ public void startActivity(Activity parentActivity) {
       runDefaultActivity(parentActivity, intent);
     } else if (targetIntents.size() == 1) {
       runFirstAndOnlyOneActivity(parentActivity, targetIntents.get(0));
-    } else {
+    } else if (targetIntents.size() > 0){
```
Comment (jakubkrolewski) [inline slinger/src/main/java/pl/allegro/android/slinger/IntentStarter.java]: !targetIntents.isEmpty()

File: slinger/src/test/java/pl/allegro/android/slinger/AppLinkBypasserTest.java [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+
+  @Test public void intentShouldContainOnlyUriWithScheme() {
+    // given
+    Intent intent = new Intent().setData(parse("http://example.com"));
+
+    // when
+    Intent rawSchemeIntent = objectUnderTest.getIntentWithRawSchemeUri(intent);
+
+    // then
+    assertThat(rawSchemeIntent.getScheme()).isEqualTo(intent.getScheme());
```
Comment (jakubkrolewski) [inline slinger/src/test/java/pl/allegro/android/slinger/AppLinkBypasserTest.java:37]: consider using https://github.com/square/assertj-android/blob/master/assertj-android/src/main/java/org/assertj/android/api/content/IntentAssert.java

Comment (kkocel) [inline slinger/src/test/java/pl/allegro/android/slinger/AppLinkBypasserTest.java:37]: What if I'm using Truth?

File: slinger/src/main/java/pl/allegro/android/slinger/IntentStarter.java (hunk 3 above)
Comment (kkocel) [inline slinger/src/main/java/pl/allegro/android/slinger/IntentStarter.java]: done

File: slinger/src/main/java/pl/allegro/android/slinger/IntentStarter.java [hunk 5]
```diff
@@ -82,6 +84,12 @@ void resolveActivities() {
     wasResolved = true;
     List<ResolveInfo> queryIntentActivities = packageManager.queryIntentActivities(intent, 0);
 
+    AppLinkBypasser appLinkBypasser = new AppLinkBypasser(packageManager);
```
Comment (aziemski) [inline slinger/src/main/java/pl/allegro/android/slinger/IntentStarter.java]: pass AppLinkBypasser via constructor
